"""initial migration

Revision ID: 37770ef824f6
Revises: e348eba4fa2d
Create Date: 2024-03-01 18:14:53.377897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37770ef824f6'
down_revision = 'e348eba4fa2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
